import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'drizzle/**',
      'playwright-report/**',
      'test-results/**',
      // Generated output, gitignored as `/coverage/` — the one build directory this list
      // was missing. `vitest --coverage` writes a provider's instrumented copies here, so
      // without this line any coverage run reds `pnpm lint` on files nobody wrote. Found at
      // the 02-15 gate, where a gitignored read-only production helper parked here failed
      // `no-explicit-any` and blocked the phase gate on a file that is not in the repo.
      'coverage/**',
      'next-env.d.ts',
      // Generated shadcn copy-ins. They are never hand-edited beyond the token pass
      // (02-UI-SPEC.md), so linting them can only produce noise that someone is then
      // tempted to silence by editing a primitive.
      'src/components/ui/**',
      // Generated by `next build` / the workflow test world (04-RESEARCH Pitfall 6). The
      // builder writes bundled step/flow routes under .well-known — `eslint .` lints dot
      // folders, so without this every local build reds lint on code nobody wrote.
      'src/app/.well-known/workflow/**',
      // Generated by `next build` / the workflow test world (04-RESEARCH Pitfall 6): the
      // local world's run state.
      '.workflow-data/**',
      // Generated by `next build` / the workflow test world (04-RESEARCH Pitfall 6): the
      // @workflow/vitest plugin's compiled bundles and run state.
      '.workflow-vitest/**',
    ],
  },
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
  // First React rules in this repo. Phase 1 had no hooks at all; plan 02-10's debounced
  // estimate is the first hook-heavy code, and nothing in the config above would catch a
  // single hook mistake. rules-of-hooks is an error because violating it is a runtime
  // bug, not a style opinion; exhaustive-deps is an error too, because a missing
  // dependency on a debounced estimate is exactly how a stale figure repaints over a
  // fresh one (02-RESEARCH.md Pitfall 5).
  {
    files: ['src/**/*.ts', 'src/**/*.tsx'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
    },
  },
);
